# .github/workflows/ci.yml

name: c/c++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build the code
        run: make

      - name: Run tests
        run: ./tests/test_binary  # Replace with actual test binary
        continue-on-error: true  # <-- This allows this step to fail without failing the job